
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 73
#define YY_END_OF_BUFFER 74
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[369] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   74,   72,   69,   70,   71,   70,   41,    8,
       68,   39,   72,   35,   45,   27,   43,   28,   38,   72,
       29,   23,   22,   47,   37,   26,   32,   68,   68,   36,
       46,   51,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   33,   72,
       44,    3,    2,    2,    6,    5,    5,    6,   73,   20,
       19,   19,   18,   17,   13,   14,   15,   16,   12,   11,
       11,   10,    9,   70,   40,   68,   25,   67,   48,   21,
        0,    4,    1,   21,    0,    0,    0,   22,   22,    0,

       49,   34,   30,   31,   50,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   67,   68,
       68,   68,   68,   68,   68,   68,   68,   57,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   42,    2,    5,
        7,   19,   11,   21,    0,    0,    0,   21,    0,    0,
       21,    0,   22,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   67,   68,   68,   68,   58,   68,
       68,   67,   68,   68,   68,   68,   68,   68,   68,   68,

       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,    0,   21,   21,    0,   21,    0,    0,   21,   21,
        0,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   56,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   24,   65,   68,
       68,   21,    0,    0,   21,   21,    0,   21,   68,   68,
       68,   68,   68,   68,   53,   68,   68,   68,   68,   67,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   67,   68,   68,   66,   21,    0,

       21,   68,   64,   67,   68,   68,   68,   68,   55,   68,
       68,   68,   68,   68,   68,   68,   68,   61,   62,   63,
       68,   68,   68,   68,   54,   67,    0,   68,   52,   68,
       68,   68,   68,   68,   68,   68,   68,   68,    0,    0,
       68,   68,   68,   68,   68,   68,    0,    0,   68,   68,
       68,    0,    0,   68,    0,    0,   68,    0,    0,    0,
        0,    0,    0,    0,    0,   60,   59,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    4,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    6,    7,    8,    1,    9,   10,   11,    1,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   21,   21,    1,   22,   23,
       24,   25,    1,    1,   26,   26,   26,   26,   27,   26,
       26,   26,   28,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   29,   26,   26,   26,   26,   26,   26,   26,
       30,   31,   32,   33,   34,    1,   35,   36,   37,   38,

       39,   40,   41,   42,   43,   26,   44,   45,   46,   47,
       48,   49,   26,   50,   51,   52,   53,   54,   55,   56,
       57,   58,   59,   60,   61,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[62] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        2,    1,    1,    1,    1,    2,    2,    2,    2,    1,
        1,    1,    1,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    1,    1,
        1
    } ;

static const flex_int16_t yy_base[375] =
    {   0,
        0,    0,   59,   60,   63,   64,    0,    0,   67,   68,
       78,   79,  537,  538,  538,  538,  538,  533,  511,  538,
        0,  538,  523,  538,  538,  538,  518,  538,   63,   71,
       60,  103,  107,  538,   66,  508,   69,  484,   43,  538,
      538,  538,   60,   55,   87,   58,   57,  104,  482,   98,
      481,  101,   98,  489,  108,  114,  479,  484,  538,  465,
      538,  538,  538,  521,  538,  538,  520,  503,  538,  538,
      538,  518,  538,  538,  538,  538,  538,  538,  538,  538,
      517,  538,  538,  538,  538,    0,  538,  538,  538,  146,
      480,  538,  538,  148,  156,  138,  150,  171,  179,  173,

      538,  538,  538,  538,  538,  466,  467,  465,  464,  463,
      465,  473,  459,  127,  475,  474,  461,  467,  453,  454,
      451,  451,  457,  454,  452,  449,  446,    0,  448,  130,
      449,  443,  439,  448,  455,   83,  455,  438,  441,  122,
      439,  444,  439,  153,  151,  166,  442,  538,  538,  538,
      538,  538,  538,  194,  202,  204,  437,  209,  220,  181,
      211,  226,  234,  444,  439,  429,  428,  440,  433,  442,
      437,  436,  437,  423,  421,  175,  436,  434,  430,  422,
      428,  415,  430,  429,    0,  415,  194,  410,  422,  419,
      416,    0,  413,  413,  402,  403,  409,  400,  402,  399,

      407,  410,  396,  410,  395,  397,  397,  404,  404,  406,
      395,  229,  236,  242,  398,  251,  246,  238,  254,  262,
      266,  397,  390,  397,  385,  384,  394,  388,  389,  379,
      377,  385,  374,  381,    0,  378,  385,  378,  370,  382,
      370,  384,  368,  363,  381,  380,  375,  370,  362,  359,
      367,  372,  358,  370,  364,  350,  353,    0,    0,  351,
      363,  271,  273,  349,  277,  281,  288,  292,  361,  358,
      352,  362,  344,  360,    0,  347,  348,  353,  353,  345,
      343,  336,  340,  346,  346,  343,  331,  345,  344,  333,
      342,  326,  335,  326,  324,  331,  330,    0,  297,  330,

      299,  321,    0,  352,  332,  321,  314,  314,    0,  314,
      307,  324,  325,  326,  321,  320,  306,    0,    0,    0,
      317,  308,  316,  309,  538,  335,  304,  299,    0,  311,
      302,  309,  310,  307,  296,  297,  285,  291,  280,  275,
      275,  277,  285,  285,  278,  262,  275,  254,  252,  259,
      237,  239,  266,  240,  226,  215,  213,  195,  170,  188,
      169,  141,  115,   91,   49,  538,  538,  538,  333,  335,
      337,  339,  341,   83
    } ;

static const flex_int16_t yy_def[375] =
    {   0,
      368,    1,  369,  369,  370,  370,  371,  371,  372,  372,
      373,  373,  368,  368,  368,  368,  368,  368,  368,  368,
      374,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  374,  374,  368,
      368,  368,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  374,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,

      368,  368,  368,  368,  368,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,

      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  368,  368,  368,  368,  368,  368,  368,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  368,  368,

      368,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  368,  374,  368,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  368,  368,
      374,  374,  374,  374,  374,  374,  368,  368,  374,  374,
      374,  368,  368,  374,  368,  368,  374,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,    0,  368,  368,
      368,  368,  368,  368
    } ;

static const flex_int16_t yy_nxt[600] =
    {   0,
       14,   15,   16,   17,   18,   15,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   21,   21,   38,   39,   40,
       14,   41,   42,   21,   43,   44,   45,   46,   47,   48,
       49,   21,   50,   21,   51,   21,   52,   21,   53,   54,
       55,   56,   21,   57,   58,   21,   21,   21,   59,   60,
       61,   63,   63,   64,   64,   66,   66,   67,   67,   71,
       71,   72,   72,   92,   73,   73,   68,   68,   93,   88,
       80,   80,   81,   81,   86,   82,   82,   89,  101,  102,
       90,   90,  104,  105,  107,  109,  118,   74,   74,  108,

      367,  120,  111,  121,  112,  119,   75,   75,   83,   83,
      110,  113,  122,   76,   76,   91,   77,   77,   78,   78,
       94,  114,   95,   95,   94,  195,   98,   99,  115,   96,
      196,  116,  135,   96,  117,  132,   97,  128,  123,  133,
      100,   96,  366,  129,  130,   96,  124,  136,  125,  139,
      137,  126,  160,  134,  160,  144,  200,  161,  161,  140,
      141,  365,  142,  145,  143,  154,  154,  158,  158,  162,
      162,  201,  155,   94,  159,   95,   95,  172,  173,  156,
      188,  189,   96,   97,  155,  207,  159,  364,   94,   97,
       98,   98,  163,  163,   96,  205,   94,   96,   98,   99,

      161,  161,  206,  208,  100,   96,  100,  185,  209,   96,
      210,  363,  100,  154,  154,  362,  212,   96,  212,  361,
      155,  213,  213,  214,  214,  231,  232,  156,  216,  216,
      220,  220,  155,  360,  218,  159,  218,  156,  240,  219,
      219,  241,  217,   94,  221,   95,   95,  159,  213,  213,
      185,   94,   96,   98,   98,  262,  262,  219,  219,   97,
       96,  154,  154,  359,   96,  265,  265,  100,  155,  263,
      216,  216,   96,  266,  266,  156,  358,  159,  357,  217,
      155,  220,  220,  356,  217,  268,  268,  267,  355,  159,
      262,  262,  299,  299,  354,  221,  216,  216,  185,  221,

      266,  266,  192,  159,  263,  353,  263,  301,  301,  352,
      217,  220,  220,  192,  267,  159,  262,  262,  266,  266,
      351,  267,  192,  185,  350,  221,  349,  348,  347,  192,
      263,  346,  267,   62,   62,   65,   65,   69,   69,   70,
       70,   79,   79,  345,  185,  344,  343,  342,  341,  185,
      185,  340,  339,  338,  337,  336,  335,  334,  185,  192,
      333,  332,  331,  185,  185,  185,  330,  329,  328,  327,
      326,  325,  324,  323,  185,  322,  185,  321,  320,  319,
      318,  317,  316,  315,  192,  314,  313,  192,  312,  311,
      310,  309,  308,  307,  306,  185,  305,  304,  303,  302,

      300,  298,  297,  296,  295,  294,  293,  192,  292,  291,
      192,  290,  289,  288,  287,  286,  285,  284,  283,  282,
      281,  192,  280,  258,  279,  278,  277,  276,  185,  275,
      185,  185,  274,  273,  272,  271,  270,  269,  264,  261,
      260,  259,  258,  257,  256,  192,  255,  254,  253,  252,
      251,  250,  249,  248,  247,  246,  245,  192,  244,  192,
      243,  242,  185,  239,  238,  237,  236,  192,  235,  234,
      233,  230,  185,  229,  185,  185,  228,  227,  226,  225,
      224,  223,  222,  215,  211,  204,  203,  202,  199,  198,
      197,  194,  193,  192,  191,  190,  187,  186,  185,  184,

      183,  182,  181,  180,  179,  178,  177,  176,  175,  174,
      171,  170,  169,  168,  167,  166,  165,  164,  157,  153,
      152,  151,  150,  149,  148,  147,  146,  138,  131,  127,
      106,  103,   88,   87,   85,   84,  368,   13,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368

    } ;

static const flex_int16_t yy_chk[600] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    3,    4,    5,    6,    5,    6,    9,
       10,    9,   10,   31,    9,   10,    5,    6,   31,   29,
       11,   12,   11,   12,  374,   11,   12,   29,   35,   35,
       30,   30,   37,   37,   39,   43,   46,    9,   10,   39,

      365,   47,   44,   47,   44,   46,    9,   10,   11,   12,
       43,   44,   47,    9,   10,   30,    9,   10,    9,   10,
       32,   45,   32,   32,   33,  136,   33,   33,   45,   32,
      136,   45,   53,   33,   45,   52,   32,   50,   48,   52,
       33,   32,  364,   50,   50,   33,   48,   53,   48,   55,
       53,   48,   96,   52,   96,   56,  140,   96,   96,   55,
       55,  363,   55,   56,   55,   90,   90,   94,   94,   97,
       97,  140,   90,   95,   94,   95,   95,  114,  114,   90,
      130,  130,   95,   97,   90,  145,   94,  362,   98,   95,
       98,   98,  100,  100,   95,  144,   99,   98,   99,   99,

      160,  160,  144,  145,   98,   99,  100,  145,  146,   98,
      146,  361,   99,  154,  154,  360,  155,   99,  155,  359,
      154,  155,  155,  156,  156,  176,  176,  154,  158,  158,
      161,  161,  154,  358,  159,  158,  159,  156,  187,  159,
      159,  187,  158,  162,  161,  162,  162,  158,  212,  212,
      357,  163,  162,  163,  163,  213,  213,  218,  218,  162,
      163,  214,  214,  356,  162,  217,  217,  163,  214,  213,
      216,  216,  163,  219,  219,  214,  355,  216,  354,  217,
      214,  220,  220,  353,  216,  221,  221,  219,  352,  216,
      262,  262,  263,  263,  351,  220,  265,  265,  350,  221,

      266,  266,  349,  265,  262,  348,  263,  267,  267,  347,
      265,  268,  268,  346,  266,  265,  299,  299,  301,  301,
      345,  267,  344,  343,  342,  268,  341,  340,  339,  338,
      299,  337,  301,  369,  369,  370,  370,  371,  371,  372,
      372,  373,  373,  336,  335,  334,  333,  332,  331,  330,
      328,  327,  326,  324,  323,  322,  321,  317,  316,  315,
      314,  313,  312,  311,  310,  308,  307,  306,  305,  304,
      302,  300,  297,  296,  295,  294,  293,  292,  291,  290,
      289,  288,  287,  286,  285,  284,  283,  282,  281,  280,
      279,  278,  277,  276,  274,  273,  272,  271,  270,  269,

      264,  261,  260,  257,  256,  255,  254,  253,  252,  251,
      250,  249,  248,  247,  246,  245,  244,  243,  242,  241,
      240,  239,  238,  237,  236,  234,  233,  232,  231,  230,
      229,  228,  227,  226,  225,  224,  223,  222,  215,  211,
      210,  209,  208,  207,  206,  205,  204,  203,  202,  201,
      200,  199,  198,  197,  196,  195,  194,  193,  191,  190,
      189,  188,  186,  184,  183,  182,  181,  180,  179,  178,
      177,  175,  174,  173,  172,  171,  170,  169,  168,  167,
      166,  165,  164,  157,  147,  143,  142,  141,  139,  138,
      137,  135,  134,  133,  132,  131,  129,  127,  126,  125,

      124,  123,  122,  121,  120,  119,  118,  117,  116,  115,
      113,  112,  111,  110,  109,  108,  107,  106,   91,   81,
       72,   68,   67,   64,   60,   58,   57,   54,   51,   49,
       38,   36,   27,   23,   19,   18,   13,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368

    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[74] =
    {   0,
0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "jucompiler.l"
/*********************************************
*
*           Andre Leite - 2015250489
*           Lucas Ferreira - 2016243439
*
**********************************************/
#line 10 "jucompiler.l"
  #include <stdio.h>
  #include <stdlib.h>
  #include <string.h>
  #include <math.h>
  #include <ctype.h>
  #include <locale.h>
  #include "y.tab.h"
  #include "SyntaxTree.h"
  #include "SymTable.h"


  int l = 0;
  int e1 = 0;
  int e2 = 0;
  int s1 = 0;
  int lineCounter = 1;
  int lineOpCounter = 0;
  int columnCounter = 1;
  int strtoken = 0;
  int terminated = 0;
  int initString = 0;
  int initline =0;
  int error = 0;
  int semantics = 0;

  char *line[25];
  char strlit[250];
  char toend[250];
  int fatalities=0;

  extern Node *root;

  void updateArray(char* input){
      line[lineOpCounter]=input;
      lineOpCounter++;
  }

  void printStrlit(){
      if(strlit[0]!='\"'){
          return;
      }
      else{
          if(l == 1){
              printf("STRLIT(%s)\n",strlit);
          }
          strtoken=0;
          memset(strlit,0,sizeof(strlit));
      }
  }

  int checkTerminated(){
      int aAspas=0;
      int fAspas=0;
      for(int i=0;i<lineOpCounter;i++){
          if(strcmp(line[i],"fecha-aspas")==0){
              fAspas++;
          }
          if(strcmp(line[i],"abre-aspa")==0){
              aAspas++;
          }
      }
      if(aAspas==fAspas){
          return 1;
      }
      else{
          memset(strlit,0,sizeof(strlit));
          return 0;
      }
  }
  
  void makepacket(int col, char *t){
    yylval.loki = (Uni *)malloc(sizeof(Uni));
    yylval.loki->id = strdup(t);
    yylval.loki->column = col-strlen(t);
  }

#line 806 "lex.yy.c"

#line 808 "lex.yy.c"

#define INITIAL 0
#define LINE_COMMENT 1
#define COMMENT 2
#define ESCAPE 3
#define ESCAPE_STR 4
#define STR 5

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 150 "jucompiler.l"


#line 1033 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 369 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 538 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 152 "jucompiler.l"
{columnCounter+=yyleng;BEGIN LINE_COMMENT;}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 153 "jucompiler.l"
{columnCounter=1;BEGIN 0;lineCounter++;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 154 "jucompiler.l"
{columnCounter+=yyleng;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 156 "jucompiler.l"
{initline = lineCounter; initString = columnCounter;columnCounter+=yyleng;BEGIN COMMENT;}
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 157 "jucompiler.l"
{columnCounter=1;lineCounter++;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 158 "jucompiler.l"
{columnCounter+=yyleng;}
	YY_BREAK
case YY_STATE_EOF(COMMENT):
#line 159 "jucompiler.l"
{printf("Line %d, col %d: unterminated comment\n",initline,initString);initString=0;initline=0;BEGIN 0;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 160 "jucompiler.l"
{columnCounter+=yyleng;BEGIN 0;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 162 "jucompiler.l"
{memset(strlit,0,sizeof(strlit));updateArray("abre-aspa");strcat(strlit,yytext);initString=columnCounter;columnCounter+=yyleng;error=0;BEGIN STR;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 163 "jucompiler.l"
{strcat(strlit,yytext);BEGIN ESCAPE_STR;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 164 "jucompiler.l"
{columnCounter+=yyleng;strcat(strlit,yytext);updateArray("fecha-aspas");yylval.loki = malloc(sizeof(Uni));if(error!=1){if(l==-1){yylval.loki->id = strdup(strlit);yytext=strdup(yylval.loki->id );error=0;BEGIN 0;yylval.loki->column =columnCounter-strlen(strlit);return STRLIT;}else{printStrlit();};}else{memset(strlit,0,sizeof(strlit));};error=0;BEGIN 0;}
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 165 "jucompiler.l"
{columnCounter+=yyleng;terminated=checkTerminated();if(terminated == 0 && e1 == 1){printf("Line %d, col %d: unterminated string literal\n",lineCounter,initString);};lineCounter++;columnCounter=1;lineOpCounter=0;BEGIN 0;}
	YY_BREAK
case YY_STATE_EOF(STR):
#line 166 "jucompiler.l"
{columnCounter+=yyleng;terminated=checkTerminated();if(e1 == 1){printf("Line %d, col %d: unterminated string literal\n",lineCounter,initString);};lineCounter++;lineOpCounter=0;BEGIN 0;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 167 "jucompiler.l"
{columnCounter+=yyleng;strcat(strlit,yytext);}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 169 "jucompiler.l"
{columnCounter+=yyleng+1;strcat(strlit,yytext);BEGIN STR;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 170 "jucompiler.l"
{columnCounter+=yyleng+1;strcat(strlit,yytext);BEGIN STR;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 171 "jucompiler.l"
{columnCounter+=yyleng+1;strcat(strlit,yytext);BEGIN STR;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 172 "jucompiler.l"
{columnCounter+=yyleng+1;strcat(strlit,yytext);BEGIN STR;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 173 "jucompiler.l"
{columnCounter+=yyleng+1;strcat(strlit,yytext);BEGIN STR;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 174 "jucompiler.l"
{columnCounter+=yyleng+1;strcat(strlit,yytext);BEGIN STR;}
	YY_BREAK
case 19:
/* rule 19 can match eol */
YY_RULE_SETUP
#line 175 "jucompiler.l"
{if(e1 == 1){printf("Line %d, col %d: invalid escape sequence (\\%s)\n",lineCounter,columnCounter,"");};terminated=checkTerminated();if(terminated == 0 && e1 == 1 && l != -1){printf("Line %d, col %d: unterminated string literal\n",lineCounter,initString);};error=1;memset(strlit,0,sizeof(strlit));lineCounter++;columnCounter=1;lineOpCounter=0;BEGIN 0;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 176 "jucompiler.l"
{strcat(strlit,yytext);if(e1 == 1){printf("Line %d, col %d: invalid escape sequence (\\%s)\n",lineCounter,columnCounter,yytext);};columnCounter+=yyleng+1;error=1;BEGIN STR;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 178 "jucompiler.l"
{if(l==1){printf("REALLIT(%s)\n", yytext);};columnCounter+=yyleng;updateArray("reallit");if(l == -1){makepacket(columnCounter,yytext); return REALLIT;};}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 179 "jucompiler.l"
{if(l==1){printf("INTLIT(%s)\n", yytext);};columnCounter+=yyleng;updateArray("intlit");if(l == -1){makepacket(columnCounter,yytext); return INTLIT;};}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 180 "jucompiler.l"
{if(l==1){printf("INTLIT(%s)\n", yytext);};columnCounter+=yyleng;updateArray("intlit");if(l == -1){makepacket(columnCounter,yytext); return INTLIT;};}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 181 "jucompiler.l"
{if(l==1){printf("BOOLLIT(%s)\n",yytext);};columnCounter+=yyleng;updateArray("boollit");if(l == -1){makepacket(columnCounter,yytext); return BOOLLIT;};}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 182 "jucompiler.l"
{if(l==1){printf("AND\n");};columnCounter+=yyleng;updateArray("and");if(l == -1){return AND;};}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 183 "jucompiler.l"
{if(l==1){printf("ASSIGN\n");};columnCounter+=yyleng;updateArray("assign");if(l == -1){yylval.col = columnCounter-yyleng;return ASSIGN;};}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 184 "jucompiler.l"
{if(l==1){printf("STAR\n");};columnCounter+=yyleng;updateArray("star");if(l == -1){return STAR;};}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 185 "jucompiler.l"
{if(l==1){printf("COMMA\n");};columnCounter+=yyleng;updateArray("comma");if(l == -1){return COMMA;};}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 186 "jucompiler.l"
{if(l==1){printf("DIV\n");};columnCounter+=yyleng;updateArray("div");if(l == -1){return DIV;};}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 187 "jucompiler.l"
{if(l==1){printf("EQ\n");};columnCounter+=yyleng;updateArray("eq");if(l == -1){return EQ;};}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 188 "jucompiler.l"
{if(l==1){printf("GE\n");};columnCounter+=yyleng;updateArray("ge");if(l == -1){return GE;};}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 189 "jucompiler.l"
{if(l==1){printf("GT\n");};columnCounter+=yyleng;updateArray("gt");if(l == -1){return GT;};}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 190 "jucompiler.l"
{if(l==1){printf("LBRACE\n");};columnCounter+=yyleng;updateArray("lbrace");if(l == -1){return LBRACE;};}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 191 "jucompiler.l"
{if(l==1){printf("LE\n");};columnCounter+=yyleng;updateArray("le");if(l == -1){return LE;};}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 192 "jucompiler.l"
{if(l==1){printf("LPAR\n");};columnCounter+=yyleng;updateArray("lpar");if(l == -1){return LPAR;};}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 193 "jucompiler.l"
{if(l==1){printf("LSQ\n");};columnCounter+=yyleng;updateArray("lsq");if(l == -1){return LSQ;};}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 194 "jucompiler.l"
{if(l==1){printf("LT\n");};columnCounter+=yyleng;updateArray("less");if(l == -1){return LT;};}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 195 "jucompiler.l"
{if(l==1){printf("MINUS\n");};columnCounter+=yyleng;updateArray("minus");if(l == -1){return MINUS;};}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 196 "jucompiler.l"
{if(l==1){printf("MOD\n");};columnCounter+=yyleng;updateArray("mod");if(l == -1){return MOD;};}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 197 "jucompiler.l"
{if(l==1){printf("NE\n");};columnCounter+=yyleng;updateArray("ne");if(l == -1){return NE;};}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 198 "jucompiler.l"
{if(l==1){printf("NOT\n");};columnCounter+=yyleng;updateArray("not");if(l == -1){return NOT;};}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 199 "jucompiler.l"
{if(l==1){printf("OR\n");};columnCounter+=yyleng;updateArray("or");if(l == -1){return OR;};}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 200 "jucompiler.l"
{if(l==1){printf("PLUS\n");};columnCounter+=yyleng;updateArray("plus");if(l == -1){return PLUS;};}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 201 "jucompiler.l"
{if(l==1){printf("RBRACE\n");};columnCounter+=yyleng;updateArray("rbrace");if(l == -1){return RBRACE;};}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 202 "jucompiler.l"
{if(l==1){printf("RPAR\n");};columnCounter+=yyleng;updateArray("rpar");if(l == -1){return RPAR;};}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 203 "jucompiler.l"
{if(l==1){printf("RSQ\n");};columnCounter+=yyleng;updateArray("rsq");if(l == -1){return RSQ;};}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 204 "jucompiler.l"
{if(l==1){printf("SEMICOLON\n");};columnCounter+=yyleng;updateArray("semicolon");memset(strlit,0,sizeof(strlit));if(l == -1){return SEMICOLON;};}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 205 "jucompiler.l"
{if(l==1){printf("ARROW\n");};columnCounter+=yyleng;updateArray("arrow");if(l == -1){return ARROW;};}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 206 "jucompiler.l"
{if(l==1){printf("LSHIFT\n");};columnCounter+=yyleng;updateArray("lshift");if(l == -1){return LSHIFT;};}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 207 "jucompiler.l"
{if(l==1){printf("RSHIFT\n");};columnCounter+=yyleng;updateArray("rshift");if(l == -1){return RSHIFT;};}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 208 "jucompiler.l"
{if(l==1){printf("XOR\n");};columnCounter+=yyleng;updateArray("xor");if(l == -1){return XOR;};}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 209 "jucompiler.l"
{if(l==1){printf("BOOL\n");};columnCounter+=yyleng;updateArray("bool");if(l == -1){return BOOL;};}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 210 "jucompiler.l"
{if(l==1){printf("CLASS\n");};columnCounter+=yyleng;updateArray("class");if(l == -1){return CLASS;};}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 211 "jucompiler.l"
{if(l==1){printf("DOTLENGTH\n");};columnCounter+=yyleng;updateArray("dotlength");if(l == -1){return DOTLENGTH;};}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 212 "jucompiler.l"
{if(l==1){printf("DOUBLE\n");};columnCounter+=yyleng;updateArray("double");if(l == -1){return DOUBLE;};}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 213 "jucompiler.l"
{if(l==1){printf("ELSE\n");};columnCounter+=yyleng;updateArray("else");if(l == -1){return ELSE;};}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 214 "jucompiler.l"
{if(l==1){printf("IF\n");};columnCounter+=yyleng;updateArray("if");if(l == -1){return IF;};}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 215 "jucompiler.l"
{if(l==1){printf("INT\n");};columnCounter+=yyleng;updateArray("int");if(l == -1){return INT;};}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 216 "jucompiler.l"
{if(l==1){printf("PRINT\n");};columnCounter+=yyleng;updateArray("print");if(l == -1){return PRINT;};}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 217 "jucompiler.l"
{if(l==1){printf("PARSEINT\n");};columnCounter+=yyleng;updateArray("parseint");if(l == -1){yylval.col = columnCounter-yyleng;return PARSEINT;};}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 218 "jucompiler.l"
{if(l==1){printf("PUBLIC\n");};columnCounter+=yyleng;updateArray("public");if(l == -1){return PUBLIC;};}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 219 "jucompiler.l"
{if(l==1){printf("RETURN\n");};columnCounter+=yyleng;updateArray("reserved");if(l == -1){return RETURN;};}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 220 "jucompiler.l"
{if(l==1){printf("STATIC\n");};columnCounter+=yyleng;updateArray("static");if(l == -1){return STATIC;};}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 221 "jucompiler.l"
{if(l==1){printf("STRING\n");};columnCounter+=yyleng;updateArray("string");if(l == -1){return STRING;};}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 222 "jucompiler.l"
{if(l==1){printf("VOID\n");};columnCounter+=yyleng;updateArray("void");if(l == -1){return VOID;};}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 223 "jucompiler.l"
{if(l==1){printf("WHILE\n");};columnCounter+=yyleng;updateArray("while");if(l == -1){return WHILE;};}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 224 "jucompiler.l"
{if(l==1){printf("RESERVED(%s)\n",yytext);};columnCounter+=yyleng;updateArray("reserved");if(l == -1){makepacket(columnCounter,yytext); return RESERVED;};}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 225 "jucompiler.l"
{if(l==1){printf("ID(%s)\n", yytext);};columnCounter+=yyleng;updateArray("id");if(l == -1){makepacket(columnCounter,yytext);return ID;};}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 226 "jucompiler.l"
{columnCounter+=yyleng;}
	YY_BREAK
case 70:
/* rule 70 can match eol */
YY_RULE_SETUP
#line 227 "jucompiler.l"
{lineCounter++;columnCounter=1;lineOpCounter=0;memset(strlit,0,sizeof(strlit));}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 228 "jucompiler.l"
{columnCounter+=yyleng;}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(LINE_COMMENT):
case YY_STATE_EOF(ESCAPE):
case YY_STATE_EOF(ESCAPE_STR):
#line 229 "jucompiler.l"
{yyterminate();}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 230 "jucompiler.l"
{if(e1 == 1){printf("Line %d, col %d: illegal character (%s)\n",lineCounter,columnCounter,yytext);};columnCounter+=yyleng;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 232 "jucompiler.l"
ECHO;
	YY_BREAK
#line 1485 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 369 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 369 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 368);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 232 "jucompiler.l"


int main(int argc, char* argv[]){
  for(int i=0;i<argc;i++){
  
      if(argv[1] == NULL){    
          l = -1;
          e1 = 1;
          e2 = 2;
          s1 = 1;
          semantics = 1;
      }else if(strcmp(argv[i],"-l")==0){
          l = 1;
          e1 = 1;
      }else if(strcmp(argv[i],"-e1")==0){
          e1 = 1;
      }else if(strcmp(argv[i],"-e2")==0){
          l = -1;
          e1 = 1;
      }else if(strcmp(argv[1], "-t")==0){
			    l = -1;
          e1 = 1;
          e2 = 2;
		  }else if(strcmp(argv[1], "-s")==0){
          l = -1;
          e1 = 1;
          e2 = 2;
          s1 = 1;
      }

  }
  if(l==0 && e1==0){
    e1 = 1;
  }
  if(l==-1){
    yyparse();
    if(fatalities == 0 && e1 == 1 && e2 == 2)
    {
      /*imprime tabela*/
      if(s1 == 1){
        printThemTables(root,semantics);
        if(semantics==0){
          printThemTrees(root,0);
        }
      }else{
        /*imprime arvore*/
        printThemTrees(root,0);
      }
      /*destroi arvore*/
      destroyThemTrees(root);
    }
  }else{
    yylex();
  }

  return 0;
}

int yywrap(){
  return 1;
}
